# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: benlink/_benshikj.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'benlink/_benshikj.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62\x65nlink/_benshikj.proto\x12\x08\x62\x65nshikj\"~\n\x1a\x43heckFirmwareUpdateRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x18\n\x10\x66irmware_version\x18\x02 \x01(\x05\x12\x0c\n\x04\x62\x65ta\x18\x03 \x01(\x08\x12\x0f\n\x07user_id\x18\x04 \x01(\x03\x12\x13\n\x0binvite_code\x18\x05 \x01(\x05\"f\n\x0c\x46irmwareInfo\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0b\n\x03md5\x18\x03 \x01(\t\x12\x15\n\rrelease_notes\x18\x04 \x01(\t\x12\x14\n\x0crelease_date\x18\x05 \x01(\t\"k\n\x19\x43heckFirmwareUpdateResult\x12(\n\x08\x66irmware\x18\x01 \x01(\x0b\x32\x16.benshikj.FirmwareInfo\x12$\n\x04\x62\x61se\x18\x02 \x01(\x0b\x32\x16.benshikj.FirmwareInfo2t\n\x10\x44\x65viceManagement\x12`\n\x13\x43heckFirmwareUpdate\x12$.benshikj.CheckFirmwareUpdateRequest\x1a#.benshikj.CheckFirmwareUpdateResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'benlink._benshikj_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKFIRMWAREUPDATEREQUEST']._serialized_start=37
  _globals['_CHECKFIRMWAREUPDATEREQUEST']._serialized_end=163
  _globals['_FIRMWAREINFO']._serialized_start=165
  _globals['_FIRMWAREINFO']._serialized_end=267
  _globals['_CHECKFIRMWAREUPDATERESULT']._serialized_start=269
  _globals['_CHECKFIRMWAREUPDATERESULT']._serialized_end=376
  _globals['_DEVICEMANAGEMENT']._serialized_start=378
  _globals['_DEVICEMANAGEMENT']._serialized_end=494
# @@protoc_insertion_point(module_scope)
